name: Clean SVG Files

on:
  workflow_dispatch:

jobs:
  clean-svg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run SVG cleaner
      run: |
        cd test
        python svg_cleaner.py
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git commit -m "Clean SVG files" -a || echo "No changes to commit"
        git push
