name: Clean SVG Files

on:
  workflow_dispatch:

jobs:
  clean-svg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml
    - name: List repository contents
      run: |
        echo "Repository contents:"
        ls -R
    - name: Run SVG cleaner
      run: |
        cd test
        python svg_cleaner.py
    - name: List output contents
      run: |
        echo "Output directory contents:"
        ls -R ../output || echo "Output directory not found"
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        git commit -m "Clean SVG files" || echo "No changes to commit"
        git push || echo "Push failed"
    - name: Check for errors
      if: failure()
      run: |
        echo "The workflow failed. Please check the logs for more information."
        exit 1
